tap "homebrew/bundle"
brew "gcc"
brew "gh"
# brew "go"
brew "minimal-racket"
brew "neovim"
brew "pnpm"
brew "poetry"
brew "pyenv"
brew "ripgrep"
brew "starship"
brew "tmux"
brew "typst"
brew "zsh-autosuggestions"
brew "zsh-completions"
brew "zsh-syntax-highlighting"
# vscode "command is only available in wsl or inside a visual studio code terminal."
